pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "heisenbergzz/dev:latest"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/HeisenbergZS/trend-devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE ./Trend'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''
                        echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
                        docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                 kubectl apply -f ./k8s/deployment.yaml
                 kubectl apply -f ./k8s/service.yaml
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed. Check logs!'
        }
    }
}

